---
name: Compile PDFs

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and
      # push the changed files back to the repository.
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: xu-cheng/texlive-action@v2
        with:
          docker_image: texlive/texlive:latest
          run: |
            make

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: "*.pdf *.svg *.xdv"
